# Generated by Django 3.1.6 on 2021-02-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210210_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
